name: "PR-D 性能与体检"
description: "为 Ling-Atlas 项目添加构建体积预算与 Lighthouse 守门机制"
title: "[PR-D] 性能与体检"
labels: ["performance", "CI", "automation"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 目标
        给站点设置体积预算与 Lighthouse 守门：
        - 超限即 CI fail；
        - 本地开发与预览不受影响。

  - type: markdown
    attributes:
      value: |
        ## 🧩 任务（见下方任务清单）

  - type: checkboxes
    id: tasks
    attributes:
      label: 任务清单
      description: 请勾选已完成项（可多选）
      options:
        - label: 产物体积预算脚本
        - label: 集成 Lighthouse CI
        - label: CI 工作流
        - label: 文档更新

  - type: textarea
    id: details
    attributes:
      label: 实施说明或遇到的问题
      description: 如有特殊说明、遇到的难点或补充信息请填写（可选）
      placeholder: 详细描述你的处理过程、遇到的问题、解决思路等

  - type: markdown
    attributes:
      value: |
        ## ✅ 验收标准
        - CI 输出预算报告与 Lighthouse 分数
        - 阈值可通过环境变量调整
        - 超限时 CI fail，修复后通过
        - 不影响本地 `dev` / `preview`

  - type: markdown
    attributes:
      value: |
        ## 🔁 回滚策略
        - 临时放宽阈值（通过 env）
        - 或注释 `.codex/budget.mjs` 与 LHCI 步骤，不影响主功能
