name: "PR-K 搜索评测"
description: "建立离线指标（nDCG/MRR/Recall）与线上交替曝光（interleaving/Team Draft）对比策略，形成可重复的质量闭环"
title: "[PR-K] 搜索评测（离线指标 + 线上交替曝光）"
labels: ["search-quality", "evaluation", "telemetry", "automation"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 目标与约束
        - 建立**离线评测**（nDCG@10、MRR、Recall@K）与**线上交替曝光**（Team Draft Interleaving）闭环。
        - **不改变默认体验**：实验仅通过查询参数启用 `?variant=lex|rrf|rrf-mmr`。
        - **匿名遥测**：不记录原文查询，仅存 `qHash` 与点击位次（复用 PR-E 的最小遥测）。

  - type: markdown
    attributes:
      value: |
        ## 🧩 待办任务

        ### 1) 离线评测
        - 新增标注集：`data/gold.jsonl`（一行一条样本）
          示例：
          {"q":"分页 怎么 做","positives":["/docs/pagination#intro","/docs/pagination#api"],"negatives":["/blog/unrelated"]}
        - 新建脚本：`scripts/eval/offline.mjs`
          - 对接现有检索函数（lex/Pagefind、rrf、rrf+mmr）
          - 计算：`nDCG@10`、`MRR`、`Recall@K`（K 可配置，默认 10）
          - 输出表格到 stdout，并生成 `scripts/eval/report.json`
        - 基线守门：`scripts/eval/baseline.json`
          示例：
          { "nDCG@10": 0.62, "MRR": 0.58, "Recall@10": 0.75, "tolerance": 0.01 }
          - 结果低于基线-容差 → `process.exit(1)`
        - 环境变量：
          - `EVAL_K=10`、`EVAL_VARIANTS="lex,rrf,rrf-mmr"`、`EVAL_FAIL_ON_DROP=1`

        ### 2) 线上交替曝光（Interleaving）
        - 在 `SearchBox.vue` 支持 `?variant=lex|rrf|rrf-mmr` 强制单路；默认保持现有融合策略。
        - 增加 **Team Draft Interleaving**：
          - 将两路候选（如 `lex` 与 `rrf-mmr`）交替合并，生成统一 Top-N 列表
          - 记录点击偏好：点击命中源模型记 1 分（可加位次折扣）
          - 通过 PR-E 的 `track("search_click", { qHash, rank, url, variantA, variantB, winner })` 上报
        - UI：
          - 仅在携带 `?variant` 或 `?ab=lex-vs-rrf-mmr` 时启用 interleaving
          - 失败或未启用时，退回现有结果呈现

        ### 3) CI 集成
        - 在 build 前运行（允许阈值由 env 控制）：
          node scripts/eval/offline.mjs
        - 将 `scripts/eval/report.json` 作为 Artifact 上传；控制台打印关键指标与对比
        - 低于基线（考虑容差）→ CI fail

  - type: checkboxes
    id: acceptance
    attributes:
      label: "✅ 验收标准"
      options:
        - label: "本地运行 `node scripts/eval/offline.mjs` 能输出 nDCG@10 / MRR / Recall@K，并生成 report.json"
          required: true
        - label: "CI 中打印离线评测对比，并以 baseline 守门（低于阈值 fail）"
          required: true
        - label: "`?variant=lex|rrf|rrf-mmr` 可切换检索逻辑；不带参数时保持默认体验"
          required: true
        - label: "Interleaving 能记录点击偏好并通过 PR-E 遥测落库（仅存 hash 与位次，不存原文）"
          required: true

  - type: textarea
    id: gold-notes
    attributes:
      label: "🧾 标注数据说明"
      description: "说明 gold.jsonl 的构建原则与覆盖范围；建议包含多样意图（导航/信息/任务）与多类别文档"
      placeholder: |
        - 条目数 / 覆盖分类 / 来源
        - positives/negatives 定义与采样策略
        - 更新频率与审阅流程

  - type: textarea
    id: interleaving-notes
    attributes:
      label: "🔀 交替曝光设计"
      description: "描述 Team Draft 细节、位次折扣、平分/并列处理与“胜者”统计口径"
      placeholder: |
        - N=10；位次折扣 1/log2(1+rank)
        - 同一 URL 合并去重策略
        - 无点击/多点击时的判定规则

  - type: textarea
    id: logs
    attributes:
      label: "🧪 验证与日志"
      description: "粘贴本地/CI 指标输出与线上点击偏好聚合片段"
      placeholder: |
        [eval] k=10 variants=lex,rrf,rrf-mmr
        [eval] nDCG@10: lex=0.59 rrf=0.66 rrf-mmr=0.69
        [eval] MRR:     lex=0.53 rrf=0.60 rrf-mmr=0.63
        [eval] Recall@10: lex=0.72 rrf=0.78 rrf-mmr=0.81
        [gate] against baseline nDCG@10=0.62 tol=0.01 -> PASS
        [telemetry] interleaving winner: rrf-mmr (p=0.61, n=342)

  - type: markdown
    attributes:
      value: |
        ## ⚙️ 实施提示
        - nDCG：使用 DCG = Σ (rel_i / log2(1+i))，rel_i = 1 若命中 positives；IDCG 由理想排序求得。
        - MRR：对每个样本取命中 positives 的第一个位次 1/rank；未命中记 0。
        - Recall@K：K 内命中 positives 的比例。
        - Interleaving 推荐 Team Draft（交替抽取），并在点击时记录来源模型；支持 `?ab=a-vs-b`。
        - 与 PR-E 遥测打通时，新增字段请在 data/telemetry.json 汇总结构中登记。

  - type: markdown
    attributes:
      value: |
        ## 🔁 回滚策略
        - 关闭 `?variant` 与 `?ab` 分支；移除 interleaving 入口。
        - 在 CI 中跳过 `scripts/eval/offline.mjs`（或放宽 baseline 阈值）。
        - 搜索仍按默认融合策略执行，功能不受影响。
