name: "PR-L 多语/i18n"
description: "在不影响现有中文路径的前提下，新增英文内容与路由（/en/...）；多语 Pagefind 索引与同一语义模型（gte-small）"
title: "[PR-L] 多语/i18n（/ 与 /en/）"
labels: ["i18n", "routing", "search", "content-ops"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 目标与约束
        - **中文保持原结构**；英文内容放 `docs/content.en/**`，对应路由前缀 **`/en/`**。
        - **纯静态实现**；不改变中文现有 URL。
        - Pagefind 为 zh / en **分别建索引**；语义检索沿用 **同一模型 gte-small**，但优先返回同语结果。
        - 站点导航提供**语言切换**，可在同 slug 间互跳；若缺失对应英文，退回英文首页。

  - type: markdown
    attributes:
      value: |
        ## 🧩 待办任务

        ### 1) 目录与生成
        - 扩展 `pagegen.mjs`：
          - 同时遍历 `docs/content/**` 与 `docs/content.en/**`
          - 产出 `/en/` 的聚合页（分类/归档/标签页）
          - 生成多语 sitemap：
            - `docs/public/sitemap.xml`（zh）
            - `docs/public/sitemap.en.xml`（en）
          - （可选）RSS 按语言各一份：
            - `rss.xml`（zh），`rss.en.xml`（en）
        - BASE 子路径兼容：所有链接与静态资源需使用相对路径或 `withBase()`。

        ### 2) 语言切换
        - 新增 `docs/.vitepress/i18n.json`：导航与组件文案映射（zh/en）
        - 修改 `Layout.vue`：
          - 加语言切换 UI（按钮或下拉）
          - 规则：若当前文档存在对应英文 **slug**，跳转 `/en/<slug>`；否则跳转 `/en/` 首页
          - 反向从 `/en/...` 切回 `/...` 同 slug
        - 头部/页脚、搜索占位符等文本读取 i18n 映射

        ### 3) 搜索
        - **Pagefind**：
          - 产出 zh 与 en 两套索引（目录隔离，如 `/pagefind/zh/**` 与 `/pagefind/en/**`）
          - `SearchBox` 根据当前路径前缀或语言状态选择索引域
        - **语义检索**：
          - 沿用 `gte-small`（Transformers.js），**同语结果优先**（打分加权或先过滤后回退）
          - 当跨语查询时，保留 RRF/MMR 融合，但优先展示与当前语言一致的候选

        ### 4) CI
        - 增加英文侧死链检查：`docs/content.en/**`
        - 构建后生成并发布两份 sitemap（`sitemap.xml`、`sitemap.en.xml`）
        - （可选）分别对 zh/en 运行 Lighthouse smoke（非强制）

  - type: checkboxes
    id: acceptance
    attributes:
      label: ✅ 验收标准
      options:
        - label: `/` 与 `/en/` 路由均可访问，语言切换在同 slug 间互跳，缺失映射时跳转英文首页
          required: true
        - label: Pagefind 在两种语言下可独立检索；语义检索在当前语言下结果优先
          required: true
        - label: 生成两份 sitemap（zh / en），并通过死链检查（包含英文侧）
          required: true
        - label: 不影响既有中文 URL 与构建流程
          required: true

  - type: textarea
    id: structure
    attributes:
      label: 🧾 目录与路由设计
      description: 粘贴 `content` / `content.en` 的示例层级与 slug 对应关系；说明聚合页与 sitemap 产出位置
      placeholder: |
        docs/
          content/{cat}/{post}/index.md
          content.en/{cat-en}/{post-en}/index.md
        /en/{cat-en}/{post-en}/

  - type: textarea
    id: search-notes
    attributes:
      label: 🔎 搜索与语义融合说明
      description: 描述 zh/en Pagefind 索引的选择逻辑与语义侧“同语优先”的实现方式
      placeholder: |
        - 索引路径：/pagefind/zh/** 与 /pagefind/en/**
        - 语言判断：基于 pathname.startsWith('/en/')
        - 融合：同语加权 + RRF；不足时回退跨语补全

  - type: textarea
    id: logs
    attributes:
      label: 🧪 验证与日志
      description: 贴出本地/CI 构建日志片段（pagegen 双目录扫描、两份 sitemap、英文死链检查通过），以及搜索在 zh/en 两侧的查询示例
      placeholder: |
        [pagegen] zh: 86 docs, en: 24 docs
        [pagefind] built zh/en indexes
        [links] zh OK (0 errors), en OK (0 errors)
        [sitemap] sitemap.xml / sitemap.en.xml written

  - type: markdown
    attributes:
      value: |
        ## ⚙️ 实施提示
        - slug 映射建议在 frontmatter 中增加 `slug_en`；缺省时可根据标题自动转 slug。
        - i18n.json 中的导航项需与路由前缀一致，避免硬编码路径。
        - 搜索占位符/空态提示等 UI 文案从 i18n 读取，避免分支散落。
        - 语义同语优先可通过“语言标签匹配 + 分数加权”或“先同语检索、无结果再跨语回退”实现。

  - type: markdown
    attributes:
      value: |
        ## 🔁 回滚策略
        - 关闭 `.en` 管线（pagegen/索引/死链）；隐藏语言切换入口。
        - 中文侧路径与站点行为不受影响，搜索仍按单语模式运行。
