  Title: Snapshot & TODO after PR-L/PR-M milestones

  Body:

  ## Snapshot
  - 多语导航、供应链加固已推送到 main（最后提交：67fa0b3...）。
  - 英文示例、指南、About 页面就绪，PageGen 输出同步到 docs/en/_generated/**。
  - CI 新增 audit / license / sbom 步骤，SRI 脚本对外链哈希变化做差异阻断。

  ## TODO
  1. 扩充英文文章，让 /en/_generated/** 更丰富。
  2. 新增文章时记得运行 `npm run gen` 更新 i18n-map；保证语言切换指向正确译文。
  3. 若 CDN 资源更新：先手动验证，更新 security/sri-allowlist.json，必要时设 `SRI_ALLOW_UPDATE=true` 生成新 manifest。
  4. 在 README/文档中说明 `.well-known/sbom.json` 的用途与下载方式。
  5. 扩展 `data/gold.jsonl`，完善离线检索评测基线。
  6. 待配额恢复后继续 PR-M（SEO/OpenGraph）计划。

  > 当前 main HEAD: 67fa0b3 chore: improve link check for multilingual paths