name: CI + Deploy
permissions:
  contents: read
  pages: write
  id-token: write
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE: /ling-atlas/
      SITE_ORIGIN: https://shlxl.github.io/ling-atlas
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Node info
        run: |
          node -v
          npm -v
      - run: npm ci
      - name: 归一标签（非阻断）
        run: npm run tags:normalize
      - name: Frontmatter 校验（阻断）
        run: npm run precheck
      - name: Markdown lint
        run: npm run md:lint
      - name: 链接检查
        run: node scripts/check-links.mjs
      - name: 图片优化
        run: node scripts/img-opt.mjs
      - name: 生成聚合页（pagegen）
        run: npm run gen
      - name: Pagegen 单元测试
        run: npm run test:pagegen
      - name: 统计聚合快照
        run: node scripts/stats-lint.mjs
      - name: 上传分类标签快照
        uses: actions/upload-artifact@v4
        with:
          name: stats-snapshot
          path: data/stats.snapshot.json
      - name: 跳过 fork PR 的统计对比
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
        run: echo "Skip stats diff: forked pull requests do not have access to origin/main baseline."
      - name: 对比主干统计快照
        id: stats_diff
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        run: |
          git fetch --depth=2 origin main
          set +e
          npm run stats:diff -- --baseline origin/main:data/stats.snapshot.json --current data/stats.snapshot.json --quiet --json > stats-diff.json
          status=$?
          set -e
          echo "exit_code=${status}" >> "$GITHUB_OUTPUT"
          if [ -f stats-diff.json ]; then
            echo "has_report=true" >> "$GITHUB_OUTPUT"
            node - <<'NODE'
const fs = require('fs')
const summaryPath = process.env.GITHUB_STEP_SUMMARY
if (!summaryPath) process.exit(0)
if (!fs.existsSync('stats-diff.json')) process.exit(0)
const raw = fs.readFileSync('stats-diff.json', 'utf8').trim()
if (!raw) process.exit(0)
fs.appendFileSync(summaryPath, `### stats:diff 输出\n\n\`\`\`json\n${raw}\n\`\`\`\n`)
NODE
          fi
          echo "stats:diff exit code: ${status}"
          exit 0
      - name: 上传统计对比报告
        if: steps.stats_diff.outputs.has_report == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: stats-diff-report
          path: stats-diff.json
      - name: stats:diff 命令执行失败
        if: steps.stats_diff.outputs.exit_code == '1'
        run: |
          echo "stats:diff command failed. Check previous logs for details." >&2
          exit 1
      - name: 统计差异超出阈值
        if: steps.stats_diff.outputs.exit_code == '2'
        run: |
          echo "Detected stats snapshot differences exceeding fail threshold. See step summary or artifact for details." >&2
          exit 2
      - name: stats:diff 异常退出
        if: steps.stats_diff.outputs.exit_code != '' && steps.stats_diff.outputs.exit_code != '0' && steps.stats_diff.outputs.exit_code != '1' && steps.stats_diff.outputs.exit_code != '2'
        env:
          STATS_DIFF_EXIT_CODE: ${{ steps.stats_diff.outputs.exit_code }}
        run: |
          echo "stats:diff exited with unexpected code ${STATS_DIFF_EXIT_CODE}." >&2
          exit "${STATS_DIFF_EXIT_CODE}"
      - name: Build semantic texts
        run: npm run embeddings:build
      - name: Build knowledge chunks
        run: node scripts/chunk-build.mjs
      - name: Offline search eval
        run: node scripts/eval/offline.mjs
      - name: Generate embedding payload (占位)
        run: node scripts/embed-build.mjs
      - name: Generate summaries (soft fail)
        run: node scripts/summary.mjs || true
      - name: Generate QA pairs (soft fail)
        run: node scripts/qa-build.mjs || true
      - name: 构建 + 搜索索引（阻断）
        run: npm run build:search
      - name: Bundle budget check
        run: node .codex/budget.mjs
      - name: npm audit (non-blocking)
        run: npm run audit
      - name: License summary
        run: npm run license
      - name: Generate SBOM
        run: npm run sbom
      - name: Install Lighthouse OS Dependencies
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: sudo apt-get update && sudo apt-get install -y libnspr4
      - name: Lighthouse CI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./node_modules/.bin/lhci autorun --collect.chromeFlags="--no-sandbox"
      - name: Merge telemetry data
        run: node scripts/telemetry-merge.mjs
      - name: 上传 Pages 产物
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
