name: CI
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Node info
        run: |
          node -v
          npm -v  
      - run: npm ci
      - name: 归一标签（非阻断）
        run: npm run tags:normalize
      - name: Frontmatter 校验（阻断）
        run: npm run precheck
      - name: 生成聚合页（pagegen）
        run: npm run gen
      - name: 构建（阻断）
        run: npm run build
      - name: Build search index (Pagefind)
        run: npm run search:index
      - name: Sync pagefind to dist
        shell: bash
        run: |
          if [ -d "docs/public/pagefind" ]; then
            mkdir -p docs/.vitepress/dist/pagefind
            cp -r docs/public/pagefind/* docs/.vitepress/dist/pagefind/
          fi
