name: CI + Deploy
permissions:
  contents: read
  pages: write
  id-token: write
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE: /ling-atlas/
      SITE_ORIGIN: https://shlxl.github.io/ling-atlas
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Node info
        run: |
          node -v
          npm -v
      - run: npm ci
      - name: 归一标签（非阻断）
        run: npm run tags:normalize
      - name: Frontmatter 校验（阻断）
        run: npm run precheck
      - name: 生成聚合页（pagegen）
        run: npm run gen
      - name: Build semantic texts
        run: npm run embeddings:build
      - name: 构建 + 搜索索引（阻断）
        run: npm run build:search
      - name: 上传 Pages 产物
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
